// This file was generated by ESP3D-Configurator V1.1.0 
/*
  configuration.h - ESP3D configuration file

  Copyright (c) 2014 Luc Lebosse. All rights reserved.

  This code is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This code is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with This code; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/
#ifndef _CONFIGURATION_H
#define _CONFIGURATION_H
//Setup station as default, use AP mode first if not done
//Note: need both defined to enable it
//Uncomment and edit them to define
//#define STATION_WIFI_SSID "*********"
//#define STATION_WIFI_PASSWORD "*********"

//You can also use a different config file for SSID/password
//Just save it in same location as this configuration.h
//This file is ignored by github
#if defined __has_include
#  if __has_include ("myconfig.h")
#    include "myconfig.h"
#  endif
#endif


/************************************
*
* Serial Communications
*
* Settings and protocols
*
************************************/

// Serial Communication protocol
// Basic serial protocol, without data change
#define COMMUNICATION_PROTOCOL RAW_SERIAL

// Main serial port
#define ESP_SERIAL_OUTPUT USE_SERIAL_0
// RX=null
// TX=null

// Serial buffer size
// 512 Bytes
// Maximum size of the serial buffer
#define SERIAL_RX_BUFFER_SIZE 512

/************************************
*
* Target firmware
*
* Targeted firmware that ESP3D will communicate with
*
************************************/
// System type=3D printer

// Target firmware
// Marlin 2.x firmware
#define DEFAULT_FW MARLIN

/************************************
*
* Radio mode of ESP3D
*
* The radio mode ESP3D communicate with the network
*
************************************/

// Use WiFi 
// Enable wifi communications
#define WIFI_FEATURE 

/************************************
*
* Channels of ESP3D
*
* The way ESP3D communicate
*
************************************/

// Use webserver
// Enable http server
#define HTTP_FEATURE 

// Use telnet server
// Enable telnet light (raw tcp) communications
#define TELNET_FEATURE 

// Use Websocket server
// Enable websocket communications
#define WS_DATA_FEATURE 

// Enable notifications
// Allows to send notifications to the user
#define NOTIFICATION_FEATURE 

// Notification message when online
// The message that will be sent when the ESP is online
#define NOTIFICATION_ESP_ONLINE "Hi, %ESP_NAME% is now online at %ESP_IP%"

// Notification title message
// The title of notification
#define ESP_NOTIFICATION_TITLE "ESP3D Notification"

/************************************
*
* Discovery methods of ESP3D
*
* The discovery methods of ESP3D
*
************************************/

// Use captive portal 
// Enable captive portal in AP mode
#define CAPTIVE_PORTAL_FEATURE 

// Use mDNS discovery
// This method need `bonjour` protocol on windows, or `avahi` on linux
#define MDNS_FEATURE 

// Use Simple Service Discovery Protocol
// It is supported on Windows out of the box
#define SSDP_FEATURE 

/************************************
*
* SSDP Customization settings
*
* Customize your ESP3D
*
************************************/

// Model name
// Modele name of device
#define ESP_MODEL_NAME "Wemos D1 mini"

// Model number
// Modele number of device
#define ESP_MODEL_NUMBER "ESP3D 3.0"

// Model url
// Modele url of device
#define ESP_MODEL_URL "https://www.espressif.com/en/products/devkits"

// Manufacturer name
// Manufacturer name of device
#define ESP_MANUFACTURER_NAME "Espressif Systems"

// Manufacturer url
// Manufacturer url of device
#define ESP_MANUFACTURER_URL "https://www.espressif.com"

/************************************
*
* Flash filesystem
*
* Filesystem on flash
*
************************************/

// File system type
// LittleFS
// Type of file system used by ESP3D to store files
#define FILESYSTEM_FEATURE ESP_LITTLEFS_FILESYSTEM

/* Enable date/time on files
 * Set date/time on files using SNTP or last webui connection
 */
#define FILESYSTEM_TIMESTAMP_FEATURE

/************************************
*
* SD filesystem
*
* Filesystem on SD card
*
************************************/

// SD card connection
// Only your ESP board is connected to SDCard
// Does your system has SD card and how it is connected to your ESP3D
#define SD_DEVICE_CONNECTION ESP_NOT_SHARED_SD

// SD card library
// SDFat 2 library required
#define SD_DEVICE ESP_SDFAT2

#define SD_CARD_TYPE ESP_NORMAL_SDCARD

/* Sdio bit mode
 * Mode used by SDIO library 1 bit / 4bits
 * SD_ONE_BIT_MODE
 * SD_FOUR_BIT_MODE
 */
 #define SDIO_BIT_MODE SD_ONE_BIT_MODE

/* Enable date/time on files
 * Set date/time on files using SNTP or last webui connection
 */
#define SD_TIMESTAMP_FEATURE

/************************************
 *
 * SD card pins
 *
 ************************************/

/* SD card detect pin
 * The pin used to detect SD card
 */
#define ESP_SD_DETECT_PIN 26

/* SD card detect pin value
 * State of SD card detect pin when card is present
 */
#define ESP_SD_DETECT_VALUE 0

/* SD shared flag pin
 * The pin used to enable SD card for ESP board
 */
// #define ESP_FLAG_SHARED_SD_PIN -1

/* SD shared flag pin value
 * State of SD card shared pin for ESP board
 */
// #define ESP_FLAG_SHARED_SD_VALUE 0

/* SD card CS pin
 * The pin used to select SD card in SPI mode
 */
#define ESP_SD_CS_PIN   5
#define ESP_SD_MISO_PIN 19
#define ESP_SD_MOSI_PIN 23
#define ESP_SD_SCK_PIN  18
//#define ESP_SDIO_CMD_PIN 38
//#define ESP_SDIO_D0_PIN 40
//#define ESP_SDIO_CLK_PIN 39

/************************************
*
* Remote access
*
* Remote filesystem access
*
************************************/

// Enable global filesystem
// Allows to access to all filesystems fromsame location
#define GLOBAL_FILESYSTEM_FEATURE 

// WebDav access
// All filesystems
// Use WebDav to access to your filesystem
#define WEBDAV_FEATURE FS_ROOT

// FTP access
// ESP3D SD
// Use FTP to access to your filesystem (1 connection only)
#define FTP_FEATURE FS_ROOT

/************************************
*
* Update ESP3D
*
* Update ESP3D firmware
*
************************************/

// Enable Web Update
// Update firmware using WebUI
#define WEB_UPDATE_FEATURE 

// Enable SD card Update
// Update firmware and settings using file on SDCard
#define SD_UPDATE_FEATURE 

/************************************
*
* Display settings
*
* Rendering screens
*
************************************/

// Printer screen
// Your printer has a display
#define PRINTER_HAS_DISPLAY 

/************************************
*
* Levels of security
*
* How commands are allowed to be sent to ESP3D
*
************************************/

// Enable serial commands
// Allow commands to be sent to ESP3D via serial port
#define SERIAL_COMMAND_FEATURE 

/************************************
*
* Additional features
*
* Extra settings
*
************************************/

// Enable direct control pin
// Controls pins using [ESP201]
#define DIRECT_PIN_FEATURE 

/************************************
*
* Scripting settings
*
* Scripting on ESP3D
*
************************************/

// Enable hook when getting date/time
// Automaticaly launch script when get date/time

// Commands to run when got date/time
// Separate commands with ';'
#define ESP_GOT_DATE_TIME_HOOK "[ESP212]DATE:%ESP_DATETIME%"

/************************************
*
* Default settings for ESP3D
*
* Do not edit them
*
************************************/

// Gcode Host Feature
// This feature allows to process Gcode files like macros.
#define GCODE_HOST_FEATURE 

// Settings location
// EEPROM
// Location where ESP3D will save settings
#define ESP_SAVE_SETTINGS SETTINGS_IN_EEPROM



/************************************
*
* Development setting 
* Do not modify them for production 
************************************/

//Enable debug mode
//Do not do this when connected to printer !!!
//be noted all upload may failed if enabled
//LOG_OUTPUT_SERIAL0
//LOG_OUTPUT_SERIAL1
//LOG_OUTPUT_SERIAL2
//LOG_OUTPUT_TELNET
//LOG_OUTPUT_WEBSOCKET
#define ESP_LOG_FEATURE LOG_OUTPUT_SERIAL0

// LOG_LEVEL_NONE
// LOG_LEVEL_ERROR
// LOG_LEVEL_DEBUG
// LOG_LEVEL_VERBOSE
#define ESP3D_LOG_LEVEL LOG_LEVEL_VERBOSE


#ifdef ESP_LOG_FEATURE
#define DEBUG_BAUDRATE 115200
#define DEBUG_ESP3D_OUTPUT_PORT  8000
#endif //ESP_LOG_FEATURE

//Enable benchmark report in dev console
//#define ESP_BENCHMARK_FEATURE

//Disable sanity check at compilation
//#define ESP_NO_SANITY_CHECK


/************************************
*
* Sanity checks 
* Do not modify 
************************************/

#if defined(ESP_GOT_DATE_TIME_HOOK) || defined (SD_TIMESTAMP_FEATURE) || defined (FILESYSTEM_TIMESTAMP_FEATURE)
    #define TIMESTAMP_FEATURE
#endif //SD_TIMESTAMP_FEATURE || FILESYSTEM_TIMESTAMP_FEATURE 

#if defined(PRINTER_HAS_DISPLAY)
#define HAS_SERIAL_DISPLAY ""
#endif // PRINTER_HAS_DISPLAY

#if defined(CAMERA_DEVICE)
#if CAMERA_DEVICE==CAMERA_MODEL_ESP32_CAM_BOARD || CAMERA_DEVICE==CAMERA_MODEL_ESP32S2_CAM_BOARD
#define USE_BOARD_HEARDER 1
#endif // CAMERA_DEVICE==CAMERA_MODEL_ESP32_CAM_BOARD || CAMERA_DEVICE==CAMERA_MODEL_ESP32S2_CAM_BOARD
#endif // CAMERA_DEVICE

#if !defined(WIFI_FEATURE) && !defined(ETH_FEATURE)
#undef HTTP_FEATURE
#undef TELNET_FEATURE
#undef WEBDAV_FEATURE
#undef FTP_FEATURE
#undef WEB_UPDATE_FEATURE
#undef CAPTIVE_PORTAL_FEATURE
#undef SSDP_FEATURE
#undef MDNS_FEATURE
#undef NOTIFICATION_FEATURE
#endif

#endif //_CONFIGURATION_H


/************************************
 * ESP3D-Configurator settings snapshot
 * Re-import: Features tab → Board preset → Import configuration.h
 ************************************/
/* ESP3D_CONFIG_SNAPSHOT_BEGIN
{
  "version": 1,
  "generator": "ESP3D-Configurator",
  "configuratorVersion": "1.1.0",
  "values": {
    "targetmcu": "esp32",
    "targetflashsize": "4",
    "formfactor": "original",
    "flash_mod1": "dio",
    "flash_mode": "dio",
    "resetmethod": "ck",
    "has_psram": false,
    "memory_type": "qio_qspi",
    "serialprotocol": "RAW_SERIAL",
    "serialport": "USE_SERIAL_0",
    "ESP_RX_PIN": "-1",
    "ESP_TX_PIN": "-1",
    "serialbuffer": "512",
    "usbserial": false,
    "serialBridge": false,
    "serialBridgeport": "USE_SERIAL_1",
    "ESP_BRIDGE_RX_PIN": "-1",
    "ESP_BRIDGE_TX_PIN": "-1",
    "systemtype": "Printer3D",
    "defaultfw": "MARLIN",
    "wifi": true,
    "ethernet": false,
    "ethernetboard": "TYPE_ETH_PHY_LAN8720",
    "ethernetclock": "MODE_ETH_CLOCK_GPIO17_OUT",
    "ethernetaddress": "1",
    "ethernetpowerpin": "-1",
    "ethernetmdcpin": "-1",
    "ethernetmdiopin": "-1",
    "ethernetspiirqpin": "-1",
    "ethernetspirstpin": "-1",
    "ethernetspi": "ETHERNET_SPI_USE_SPI2",
    "ethernetspicspin": "-1",
    "ethernetspimosipin": "-1",
    "ethernetspimisopin": "-1",
    "ethernetspisckpin": "-1",
    "bluetooth": false,
    "http": true,
    "telnet": true,
    "websocket": true,
    "notifications": true,
    "notificationonline": "Hi, %ESP_NAME% is now online at %ESP_IP%",
    "notificationtitlemsg": "ESP3D Notification",
    "captive": true,
    "mdns": true,
    "ssdp": true,
    "ssdpmodelename32": "Wemos D1 mini",
    "ssdpmodelename8285": "ESP8285",
    "ssdpmodelename8266": "ESP8266",
    "ssdpmodelenamenumber": "ESP3D 3.0",
    "ssdpmodeleurl": "https://www.espressif.com/en/products/devkits",
    "ssdpmodelemanufacturername": "Espressif Systems",
    "ssdpmodelemanufacturerurl": "https://www.espressif.com",
    "flashFS": "ESP_LITTLEFS_FILESYSTEM",
    "flashTimestamp": false,
    "sdconnection": "ESP_NOT_SHARED_SD",
    "sdfs": "ESP_SDFAT2",
    "sdio": "SD_FOUR_BIT_MODE",
    "sdtimestamp": false,
    "detectsdpin": "-1",
    "sddetectvalue": "0",
    "shareflagsdpin": "-1",
    "shareflagsdvalue": "0",
    "sdcspin": "-1",
    "sdmosipin": "-1",
    "sdmisopin": "-1",
    "sdsckpin": "-1",
    "sdioclkpin": "-1",
    "sdiocmdpin": "-1",
    "sdiod0pin": "-1",
    "sdiod1pin": "-1",
    "sdiod2pin": "-1",
    "sdiod3pin": "-1",
    "globalFS": true,
    "webdav": "FS_ROOT",
    "ftp": "FS_SD",
    "resetfeature": false,
    "resetpin": "-1",
    "ota": false,
    "webupdate": true,
    "sdupdate": true,
    "printerscreen": true,
    "displaytype": "-1",
    "flipdisplay": false,
    "i2caddressoled": "0x3c",
    "oledrstpin": "-1",
    "tftledpin": "-1",
    "tftDCpin": "-1",
    "tftRSTpin": "-1",
    "tftCSpin": "-1",
    "tftMOSIpin": "-1",
    "tftSCKpin": "-1",
    "buzzerfeature": false,
    "buzzerpin": "-1",
    "sensortype": "-1",
    "i2caddresssensor": "0x76",
    "sensorpin": "-1",
    "analogsensorconverter": "v*0.588",
    "sensorunit": "C",
    "cameratype": "-1",
    "cameraflipverticaly": true,
    "camerafliphorizontaly": true,
    "CAM_LED_PIN": "4",
    "CAM_PULLUP1": "-1",
    "CAM_PULLUP2": "-1",
    "PWDN_GPIO_NUM": "32",
    "RESET_GPIO_NUM": "-1",
    "XCLK_GPIO_NUM": "0",
    "SIOD_GPIO_NUM": "26",
    "SIOC_GPIO_NUM": "27",
    "Y9_GPIO_NUM": "35",
    "Y8_GPIO_NUM": "34",
    "Y7_GPIO_NUM": "39",
    "Y6_GPIO_NUM": "36",
    "Y5_GPIO_NUM": "21",
    "Y4_GPIO_NUM": "19",
    "Y3_GPIO_NUM": "18",
    "Y2_GPIO_NUM": "5",
    "VSYNC_GPIO_NUM": "25",
    "HREF_GPIO_NUM": "23",
    "PCLK_GPIO_NUM": "22",
    "serialcmdfeature": true,
    "corsfeature": false,
    "authentication": false,
    "directpins": true,
    "autorunscript": "-1",
    "autostartcommands": "M117 Mounting SD;M21",
    "autostartfile": "autorun.gco",
    "luainterpreter": false,
    "hook_ip": false,
    "get_ip_hook": "[ESP212]IP:%ESP_IP%",
    "hook_datetime": true,
    "get_datetime_hook": "[ESP212]DATE:%ESP_DATETIME%",
    "gcodehost": true,
    "settings": "SETTINGS_IN_EEPROM"
  }
}
ESP3D_CONFIG_SNAPSHOT_END */
